sudo: required

language: gne
node_js:
  - "10"

services:
  - docker

before_install:
  - npm install -g npx
  - docker build -t janguzman/cactus_image_cdn .
  - docker images
install:
  - docker run -ti --name=cactus_img_cdn -d -e CODECOV_TOKEN=$CODECOV_TOKEN -v $(pwd)/src/img/:/app/src/img/ -p 8000:3000 janguzman/cactus_image_cdn
  - docker ps -a

script:
  - docker exec -ti cactus_img_cdn nginx -c /etc/nginx/nginx.conf -t
after_success: npx codecov