sudo: required

language: node_js
node_js:
  - "8"

services:
  - docker

before_install:
  - docker build -t janguzman/cactus_image_cdn .
  - docker images
install:
  - docker run -ti --name=cactus_img_cdn -d -v $(pwd)/src/img/:/app/src/img/ -p 8000:3000 janguzman/cactus_image_cdn
  - docker ps -a

script:
  - docker exec -ti cactus_img_cdn ava